# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'iyzi-co-test-framework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iyzi-co-test-framework

  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'SVGKit', '~> 3.0.0'

end
