# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'iyzicoSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iyzicoSDK

  pod 'Alamofire', '~> 5.4.1'
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'lottie-ios', '~> 3.2.1'
  pod 'SVGKit', '~> 3.0.0'

end
